[package]
name = "AoC_2021_01"
version = "1.0.0"
edition = "2021"

[[bin]]
name = 'part_1'
path = "part_1/main.rs"

[[bin]]
name = 'part_2'
path = "part_2/main.rs"

[[bin]]
name = 'part_2_buffer'
path = "part_2/main_buffer.rs"

[[bin]]
name = 'part_2_zip'
path = "part_2/main_zip.rs"